BEGIN;

CREATE TABLE IF NOT EXISTS Movies (
	MovieID INTEGER PRIMARY KEY AUTO_INCREMENT,
	Title VARCHAR(255) NOT NULL,
	Director VARCHAR(255),
	Genre VARCHAR(100),
	ReleaseYear INT,
	Rating DECIMAL(2,1),
	Description TEXT
);

CREATE TABLE IF NOT EXISTS Users (
	UserID INTEGER PRIMARY KEY AUTO_INCREMENT,
	FirstName VARCHAR(100) NOT NULL,
	LastName VARCHAR(100) NOT NULL,
	Email VARCHAR(255) UNIQUE NOT NULL,
	Phone VARCHAR(20),
	Password VARCHAR(255),
	JoinDate DATE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS Rentals (
	RentalID INTEGER PRIMARY KEY AUTO_INCREMENT,
	MovieID INTEGER NOT NULL,
	UserID INTEGER NOT NULL,
	StartDate DATE NOT NULL,
	ReturnDate DATE,
	Returned BOOLEAN DEFAULT FALSE,
	FOREIGN KEY (MovieID) REFERENCES Movies(MovieID) ON DELETE CASCADE,
    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Reviews (
	ReviewID INTEGER PRIMARY KEY AUTO_INCREMENT,
    UserID INTEGER NOT NULL,
    MovieID INTEGER NOT NULL,
    Rating DECIMAL(2,1) NOT NULL,
    Comment TEXT,
    FOREIGN KEY (MovieID) REFERENCES Movies(MovieID) ON DELETE CASCADE,
    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
);

COMMIT;