BEGIN;

CREATE DATABASE IF NOT EXISTS `jdbc-webapp`;
USE `jdbc-webapp`;

DROP TABLE IF EXISTS `Reviews`;
DROP TABLE IF EXISTS `Rentals`;
DROP TABLE IF EXISTS `Users`;
DROP TABLE IF EXISTS `Movies`;

CREATE TABLE IF NOT EXISTS `Movies` (
    `MovieID` INTEGER PRIMARY KEY AUTO_INCREMENT,
    `Title` VARCHAR(255) NOT NULL,
    `Director` VARCHAR(255) NOT NULL,
    `Genre` VARCHAR(100) NOT NULL,
    `ReleaseYear` INT NOT NULL,
    `Rating` DECIMAL(3,1) NOT NULL CHECK (`Rating` >= 1 AND `Rating` <= 10),
    `Description` TEXT
);

CREATE TABLE IF NOT EXISTS `Users` (
    `UserID` INTEGER PRIMARY KEY AUTO_INCREMENT,
    `FirstName` VARCHAR(100) NOT NULL,
    `LastName` VARCHAR(100) NOT NULL,
    `Email` VARCHAR(255) UNIQUE NOT NULL,
    `Phone` VARCHAR(20),
    `Password` VARCHAR(255) NOT NULL CHECK (LENGTH(`Password`) >= 8),
    `JoinDate` DATE NOT NULL DEFAULT (CURRENT_DATE)
);

CREATE TABLE IF NOT EXISTS `Rentals` (
    `RentalID` INTEGER PRIMARY KEY AUTO_INCREMENT,
    `MovieID` INTEGER NOT NULL,
    `UserID` INTEGER NOT NULL,
    `StartDate` DATE NOT NULL DEFAULT (CURRENT_DATE),
    `ReturnDate` DATE NOT NULL DEFAULT ((CURRENT_DATE) + INTERVAL 3 DAY),
    `Returned` BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (`MovieID`) REFERENCES `Movies`(`MovieID`) ON DELETE CASCADE,
    FOREIGN KEY (`UserID`) REFERENCES `Users`(`UserID`) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `Reviews` (
    `ReviewID` INTEGER PRIMARY KEY AUTO_INCREMENT,
    `UserID` INTEGER NOT NULL,
    `MovieID` INTEGER NOT NULL,
    `Rating` DECIMAL(3,1) NOT NULL CHECK (`Rating` >= 1 AND `Rating` <= 10),
    `Comment` TEXT,
    FOREIGN KEY (`MovieID`) REFERENCES `Movies`(`MovieID`) ON DELETE CASCADE,
    FOREIGN KEY (`UserID`) REFERENCES `Users`(`UserID`) ON DELETE CASCADE
);

COMMIT;
